# Generated by Django 4.1.3 on 2023-05-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=400, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره ثابت')),
                ('mobile', models.CharField(max_length=50, verbose_name='شماره موبایل')),
                ('email', models.CharField(max_length=50, verbose_name='ایمیل')),
                ('fax', models.CharField(max_length=50, verbose_name='فکس')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت تنظیمات',
            },
        ),
    ]
