# Generated by Django 4.1.3 on 2023-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('link', models.URLField(max_length=100, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='تصویر')),
            ],
        ),
    ]
